# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8d164127d6a989e4ac7bcd370e4d9a6bcb3fa96145d12887ec43b05bbe4f3d937e9296a452a68d2cebc981b79899992b76fd820ccf708adc2048012a29244a5

test:
  secret_key_base: 4f577697995a8f083f5add87c7ed4e0e19e6fdc3a03f52175aa8a7569b03d12fbef46f9f2126d83c6efc05e488bd810984d8c621b0d16df4661786018d033b66

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
